import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import { Roboto } from "next/font/google";
import { FlashMessageProvider } from "@/components/context/FlashMessageContext";
 

const roboto = Roboto({
  subsets: ["latin"], // or ['latin', 'cyrillic'], etc.
  weight: ["400", "700"], // optional
  display: "swap", // optional
  variable: "--font-roboto", // optional, for CSS variable use
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "duckuments",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={roboto.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <FlashMessageProvider>{children}</FlashMessageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
